[package]
name = "fastcdc-alt"
version = "0.2.1"
authors = ["Florian Gäbler", "Nathan Fiedler <nathanfiedler@fastmail.fm>"]
edition = "2018"
description = "FastCDC (content defined chunking) implementation in pure Rust with an alternative API to the original crate"
repository = "https://github.com/florian-g2/fastcdc-rs-alt"
readme = "README.md"
keywords = ["cdc", "chunking"]
license = "MIT"
exclude = [
    "test/*",
]

[features]
default = []
tokio = ["dep:tokio", "tokio-stream", "async-stream"]
futures = ["dep:futures"]

[dev-dependencies]
aes = "0.8.2"
byteorder = "1.4.3"
clap = { version = "4.2.1", features = ["cargo"] }
ctr = "0.9.2"
md-5 = "0.10.5"
memmap2 = "0.5.8"
tokio = { version = "1", features = ["fs", "io-util", "rt", "rt-multi-thread", "macros"] }
futures-test = { version = "0.3" }

[dependencies]
futures = { version = "0.3", optional = true }
tokio = { version = "1", features = ["io-util"], optional = true }
tokio-stream = { version = "0.1", optional = true }
async-stream = { version = "0.3", optional = true }

[[example]]
name = "async2020"
required-features = ["tokio"]
